apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../namespaces/flux-system/gotk-components.yaml
- ../../../namespaces/flux-system/image-automation-components.yaml
- ../../../namespaces/flux-system/gotk-sync.yaml
- ../../../namespaces/flux-system/image-automation.yaml
- ../../../namespaces/flux-system/hmcts-charts.yaml
- ../../../namespaces/flux-system/
patches:
- patch: |-
    - op: add
      path: /spec/path
      value: ./clusters/cftptl  
  target: 
    group: kustomize.toolkit.fluxcd.io
    version: v1beta1
    kind: Kustomization
    name: flux-system
