apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../namespaces/flux-system/gotk-components.yaml
- ../../../namespaces/flux-system/image-automation-components.yaml
- ../../../namespaces/flux-system/gotk-sync.yaml
- ../../../namespaces/flux-system/image-automation.yaml
- ../../../namespaces/flux-system/hmcts-charts.yaml
- ../../../namespaces/flux-system/
- https://github.com/fluxcd/flux2/manifests/integrations/registry-credentials-sync/azure?ref=main
patchesStrategicMerge:
  #flux patches
- ../../../namespaces/flux-system/cftptl/gotk-sync.yaml
- ../../../namespaces/flux-system/cftptl/config-patches.yaml
