apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
spec:
  interval: 5m
  chart:
    spec:
      chart: ./stable/rpe-service-auth-provider
      sourceRef:
        kind: GitRepository
        name: hmcts
        namespace: platops
      interval: 1m
  values:
    image:
      repository: hmctspublic.azurecr.io/rpe/service-auth-provider # {"$imagepolicy": "flux-system:service-auth-provider:name"}
      tag: pro-4c8f3f28-20210531245030 # {"$imagepolicy": "flux-system:service-auth-provider:tag"}
