apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../namespaces/flux-system/gotk-components.yaml
  - ../../../namespaces/flux-system/gotk-sync.yaml
  - ../../../namespaces/flux-system/hmcts-charts.yaml
  - ../../../namespaces/flux-system/hmctspublic-charts.yaml
patchesStrategicMerge:
  #flux patches
  - ../../../namespaces/flux-system/sbox-00/gotk-sync.yaml