apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../namespaces/flux-system/gotk-components.yaml
  - ../../../namespaces/flux-system/gotk-sync.yaml
  - ../../../namespaces/flux-system/hmcts-charts.yaml
patches:
  - patch: |-
      - op: add
        path: /spec/path
        value: ./clusters/sbox-00  
    target:
      group: kustomize.toolkit.fluxcd.io
      version: v1beta1
      kind: Kustomization
      name: flux-system