apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: hmcts
  namespace: rpe
spec:
  interval: 1m
  url: https://github.com/hmcts/hmcts-charts
  ref:
    branch: master
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/stable/    