apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rpe-service-auth-provider
  namespace: rpe
spec:
  interval: 5m
  chart:
    spec:
      chart: ./stable/rpe-service-auth-provider
      sourceRef:
        kind: GitRepository
        name: hmcts
        namespace: rpe
      interval: 1m
  values:
    replicas: 2
    global:
      environment: aat