apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImageRepository
metadata:
  name: service-auth-provider
  namespace: flux-system
spec:
  image: hmctspublic.azurecr.io/rpe/service-auth-provider
  interval: 1m0s