apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: service-auth-provider
  namespace: rpe
spec:
  interval: 5m
  chart:
    spec:
      chart: ./stable/rpe-service-auth-provider
      sourceRef:
        kind: GitRepository
        name: hmcts
        namespace: rpe
      interval: 1m
  values: 
    image:
      repository: ghcr.io/stefanprodan/podinfo # {"$imagepolicy": "flux-system:podinfo:name"}
      tag: 5.0.0  # {"$imagepolicy": "flux-system:podinfo:tag"}
    java:
      replicas: 1
      image: ghcr.io/stefanprodan/podinfo:5.0.0 # {"$imagepolicy": "rpe:service-auth-provider"}
    global:
      environment: aat